export default {
  1: ["Arcade Map", "Coves Map", "Jungle Valley Map", "Pen Map"],
  2: [
    "Arena Map",
    "Crater Map",
    "Defiled Cathedral Map",
    "Fields Map",
    "Frozen Cabins Map",
    "Gardens Map",
    "Grotto Map",
    "Infested Valley Map",
    "Lair Map",
    "Moon Temple Map",
    "Peninsula Map",
    "Promenade Map",
    "Spider Forest Map",
    "Sunken City Map",
    "Tower Map",
    "Tropical Island Map",
    "Underground River Map",
    "Underground Sea Map",
    "Volcano Map",
    "Wharf Map",
  ],
  3: [
    "Ancient City Map",
    "Arid Lake Map",
    "Ashen Wood Map",
    "Basilica Map",
    "Belfry Map",
    "Canyon Map",
    "Cemetery Map",
    "Courtyard Map",
    "Factory Map",
    "Forking River Map",
    "Geode Map",
    "Glacier Map",
    "Graveyard Map",
    "Laboratory Map",
    "Lava Chamber Map",
    "Mud Geyser Map",
    "Orchard Map",
    "Overgrown Ruin Map",
    "Pier Map",
    "Plaza Map",
    "Primordial Blocks Map",
    "Reef Map",
    "Shore Map",
    "Strand Map",
    "Sulphur Vents Map",
    "Temple Map",
    "Toxic Sewer Map",
    "Vaal Pyramid Map",
  ],
  4: [
    "Academy Map",
    "Arsenal Map",
    "Bone Crypt Map",
    "Cage Map",
    "Channel Map",
    "Courthouse Map",
    "Crimson Temple Map",
    "Crystal Ore Map",
    "Desert Map",
    "Dunes Map",
    "Iceberg Map",
    "Leyline Map",
    "Lookout Map",
    "Marshes Map",
    "Museum Map",
    "Precinct Map",
    "Primordial Pool Map",
    "Ramparts Map",
    "Wasteland Map",
  ],
  5: [
    "Armoury Map",
    "Atoll Map",
    "Carcass Map",
    "Cells Map",
    "Chateau Map",
    "Desert Spring Map",
    "Haunted Mansion Map",
    "Lighthouse Map",
    "Palace Map",
    "Shrine Map",
    "Waste Pool Map",
  ],
  6: ["Malformation Map", "Silo Map"],
  7: ["Dark Forest Map", "Waterways Map"],
  8: ["Alleyways Map", "Dry Sea Map", "Racecourse Map"],
  9: [
    "Dungeon Map",
    "Mausoleum Map",
    "Mineral Pools Map",
    "Overgrown Shrine Map",
    "Relic Chambers Map",
    "Spider Lair Map",
    "Stagnation Map",
  ],
  10: [
    "Forbidden Woods Map",
    "Ghetto Map",
    "Phantasmagoria Map",
    "Scriptorium Map",
  ],
  11: [
    "Cold River Map",
    "Conservatory Map",
    "Flooded Mine Map",
    "Fungal Hollow Map",
    "Grave Trough Map",
    "Ivory Temple Map",
    "Port Map",
  ],
  12: [
    "Coral Ruins Map",
    "Crimson Township Map",
    "Dig Map",
    "Shipyard Map",
    "Siege Map",
  ],
  13: ["Cursed Crypt Map", "Maze Map", "Park Map", "Plateau Map"],
  14: [
    "Acid Caverns Map",
    "Barrows Map",
    "Beach Map",
    "Bramble Valley Map",
    "Caldera Map",
    "City Square Map",
    "Colosseum Map",
    "Core Map",
    "Excavation Map",
    "Mesa Map",
    "Residence Map",
    "Sepulchre Map",
    "Thicket Map",
  ],
  15: [
    "Arachnid Tomb Map",
    "Bazaar Map",
    "Bog Map",
    "Castle Ruins Map",
    "Colonnade Map",
    "Estuary Map",
    "Foundry Map",
    "Lava Lake Map",
    "Summit Map",
    "Terrace Map",
    "Vault Map",
    "Villa Map",
  ],
  16: [
    "Burial Chambers Map",
    "Arachnid Nest Map",
    "Pit Map",
    "Necropolis Map",
    "Vaal Temple Map",
  ],
};
