export default {
  1: ["Beach Map", "Channel Map", "Mesa Map", "Park Map"],
  2: [
    "Graveyard Map",
    "Arid Lake Map",
    "Marshes Map",
    "Iceberg Map",
    "Cage Map",
    "Haunted Mansion Map",
    "Fields Map",
    "Cemetery Map",
    "Vaal Pyramid Map",
    "Geode Map",
    "Armoury Map",
    "Tropical Island Map",
    "Estuary Map",
    "Arena Map",
    "Lair Map",
    "Dry Sea Map",
    "Overgrown Shrine Map",
    "Caldera Map",
    "Arsenal Map",
    "Plaza Map",
  ],
  3: [
    "Canyon Map",
    "Frozen Cabins Map",
    "Maze Map",
    "Ancient City Map",
    "Ivory Temple Map",
    "Barrows Map",
    "Academy Map",
    "Wharf Map",
    "Ramparts Map",
    "Infested Valley Map",
    "Moon Temple Map",
    "Sepulchre Map",
    "Temple Map",
    "Museum Map",
    "Shipyard Map",
    "Arachnid Tomb Map",
    "Bog Map",
    "Cursed Crypt Map",
    "Orchard Map",
    "Defiled Cathedral Map",
    "Summit Map",
    "Necropolis Map",
    "Racecourse Map",
    "Terrace Map",
    "Shrine Map",
    "Core Map",
    "Acid Caverns Map",
    "Basilica Map",
  ],
  4: [
    "Pen Map",
    "Fungal Hollow Map",
    "Peninsula Map",
    "Courthouse Map",
    "Strand Map",
    "Lighthouse Map",
    "Toxic Sewer Map",
    "Spider Lair Map",
    "Jungle Valley Map",
    "Ashen Wood Map",
    "Dunes Map",
    "Bone Crypt Map",
    "Bazaar Map",
    "Belfry Map",
    "Wasteland Map",
    "Promenade Map",
    "Pit Map",
    "Palace Map",
    "Sunken City Map",
  ],
  5: [
    "Desert Map",
    "City Square Map",
    "Chateau Map",
    "Volcano Map",
    "Atoll Map",
    "Arachnid Nest Map",
    "Mud Geyser Map",
    "Spider Forest Map",
    "Waterways Map",
    "Malformation Map",
    "Crimson Temple Map",
    "The Beachhead",
  ],
  6: ["Crimson Township Map", "Carcass Map"],
  7: ["Port Map", "Desert Spring Map"],
  8: ["Grotto Map", "Thicket Map", "Siege Map"],
  9: [
    "Excavation Map",
    "Grave Trough Map",
    "Underground River Map",
    "Plateau Map",
    "Vault Map",
    "Precinct Map",
    "Castle Ruins Map",
  ],
  10: [
    "Forbidden Woods Map",
    "Scriptorium Map",
    "Villa Map",
    "Dig Map",
    "The Beachhead",
  ],
  11: [
    "Relic Chambers Map",
    "Forking River Map",
    "Coral Ruins Map",
    "Colonnade Map",
    "Primordial Pool Map",
    "Dark Forest Map",
    "Bramble Valley Map",
  ],
  12: [
    "Alleyways Map",
    "Flooded Mine Map",
    "Phantasmagoria Map",
    "Laboratory Map",
    "Silo Map",
  ],
  13: ["Mausoleum Map", "Courtyard Map", "Shore Map", "Coves Map"],
  14: [
    "Glacier Map",
    "Conservatory Map",
    "Sulphur Vents Map",
    "Crater Map",
    "Lava Chamber Map",
    "Residence Map",
    "Mineral Pools Map",
    "Tower Map",
    "Waste Pool Map",
    "Pier Map",
    "Primordial Blocks Map",
    "Colosseum Map",
    "Lava Lake Map",
  ],
  15: [
    "Lookout Map",
    "Dungeon Map",
    "Leyline Map",
    "Burial Chambers Map",
    "Arcade Map",
    "Cold River Map",
    "Gardens Map",
    "Overgrown Ruin Map",
    "Factory Map",
    "Ghetto Map",
    "Reef Map",
    "Stagnation Map",
    "The Beachhead",
  ],
  16: [
    "Foundry Map",
    "Cells Map",
    "Underground Sea Map",
    "Crystal Ore Map",
    "Pit of the Chimera",
    "Lair of the Hydra",
    "Maze of the Minotaur",
    "Forge of the Phoenix",
    "Vaal Temple Map",
    "The Beachhead",
  ],
};
