name: Deploy GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: git config user.name "<user name>" && git config user.email "test@example.com"
      - run: npm run deploy
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
